# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Meta
email: vpaoloreyes@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This my blog that captures my learnings towards mastering 'Meta-Programming'
  using Ruby and RoR.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://meta.vpaoloreyes.com" # the base hostname & protocol for your site
linkedin_username: vpaoloreyes
github_username:  preyes323
twitter_username: vpaoloreyes

# Build settings
markdown: kramdown
permalink: /:title
